# Generated by Django 3.2.9 on 2021-12-01 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20211201_1055'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questions',
            old_name='attachment_file',
            new_name='file',
        ),
        migrations.RenameField(
            model_name='questions',
            old_name='replied_answer',
            new_name='reply',
        ),
        migrations.AddField(
            model_name='mentor',
            name='role',
            field=models.CharField(default='mentor', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='newuser',
            name='mentor',
            field=models.ForeignKey(db_column='mentor', default=1, on_delete=django.db.models.deletion.CASCADE, to='app.mentor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='newuser',
            name='role',
            field=models.CharField(default='student', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questions',
            name='file_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
